### ISSUE TITLE
Document ‘how do I extend tbds’ 

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/design-system#148]
I’ve noticed consumers of tbds doing things like this (these examples are from [Next Up](https://github.com/thoughtbot/nextup))…

1. Extending tbds classes to do more than it was designed to do:

    ```scss
    .tbds-app-frame__footer {
      bottom: 0;
      display: flex;
      justify-content: flex-end;
      left: 0;
      padding: $tbds-space-2 $tbds-space-4;
      position: fixed;
      width: 100%;
    }
    ```

    In this case, it may be that we aren’t explaining the job and purpose that our component is designed to do and so people expect it do more or something else. The problem with folks extending like this is that it’s very possible we’ll ship a change to the component they are extending and break their implementation. Composing project-specific CSS with its own class would be preferred.

1. Adding entirely new CSS classes to their codebase and namespacing them as a tbds class (`tbds-form__select` is not a class we offer):

    ```scss
    .tbds-form__select {
      …
    }
    ```

    This poses an issue because this is not a tbds component, but the namespaced class makes it look like it is. That’s confusing when you’re contributing to the codebase. A different and preferred solution would be to use a project-specific CSS class. It’d also be great to hear from people who have a need like this so that we can understand where we need to grow the system. How might we encourage folks to add issues to this repo?
